title: Camilo Villa
logo: assets/img/CVM_headshot_circle_small_.png
description: Power Platform Portfolio
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

collections:
  blog:
    output: true
    permalink: /blog/:name